### ISSUE TITLE
[BUG?][Blood] Cutscenes are mute when loading map with "map" command 

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1035]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When you load a map that have a cutscene before in blood (E1M1 and E4M8) the cutscene plays without any sound.
They play normally on normal play.
The Blood version is the old gog one, the cutscenes are from the movie folder of the disc image that comes with this gog version.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the cited maps with the "map" command.
2.
3.

### Your configuration

```ini
default
```

**Comment by coelckers** [comment]
fixed in 84e10beab4d735796767fc79865e8f5066869da3

**Comment by JarDrh99** [comment]
@coelckers Hello!, testing in the latest version (1.8pre-948-g6c79e35c2) it still happens (the cutscenes are muted when loading with "map" command).
Its suppossed to be fixed or it was not implemented yet?
