### ISSUE TITLE
[BUG] [Blood] Phantasm ranged attack

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1037]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Phantasms, when using the ranged attack, strangely lunge forward with the projectile, while playing an weird sound (i think its the sound of the projectile a lot of times, something like that).

They are supposed to stay in place while using this attack, sometimes they launch several ranged attacks in a row.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to a map with a phantasm (i recommend E4M4, theres an open area with one).
2. Run from him, go back and forth, he should use the attack a lot.
3.

### Your configuration

```ini
default
```

**Comment by FitzRoyX** [comment]
This only happens in 1.8.1 release build, and not in the latest master. I suggest using master builds before making bug reports, or you risk reporting issues that are already fixed. They can be found at https://github.com/ZDoom/Raze/actions Click on the one that goes to a visual studio 2022 link, not appimage

**Comment by coelckers** [comment]
Thanks for that bit of info.
1.8.x contained some refactoring that turned out to be too broken so I had to roll it back again.
I'll see to get a new release out over Christmas.

**Comment by JarDrh99** [comment]
Testing in version pre-942, it still happens, but is a bit different than before (when i first reported).
The phantasm still lunges during the attack but it does no play the sound in the weird way.
I compared to both the Fresh Supply and DOS versions, and is acting very diferently.
The map i found easist to test is E4M4, after the second building there is an open area with one.

Also, this issue section can be used to report bugs found on the development builds?

**Comment by sinisterseed** [comment]
> Also, this issue section can be used to report bugs found on the development builds?

Of course. Both stable and devbuilds. What we're less inclined to support, are self-compiled builds, as without a detailed list of configuration, or in the case of crashes, a stack trace, they tend to be useless.

**Comment by FitzRoyX** [comment]
> Testing in version pre-942, it still happens, but is a bit different than before (when i first reported). The phantasm still lunges during the attack but it does no play the sound in the weird way. I compared to both the Fresh Supply and DOS versions, and is acting very diferently. The map i found easist to test is E4M4, after the second building there is an open area with one.

To clarify: the ranged attack is supposed to look like this: phantasm stops and goes into attack animation with scythe, and a ghost missile is launched that makes its own screaming noise. In RAZE, the attack animation never happens, the missile just comes out while the phantasm is moving.
