### ISSUE TITLE
[BUG] "Address not mapped to object" when trying to run Duke 3D on 1.9

### ISSUE THREAD

**Issue by daemonspudguy** [ZDoom/Raze#1052]
### Raze version

Raze 1.9.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Relevant hardware info

AMD A8-7600

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I try to play Duke 3D, Raze segfaults. On my debug build I made, I get the error message "*** Fatal Error ***
Address not mapped to object (signal 11)
Address: (nil)"
[gdb.txt](https://github.com/ZDoom/Raze/files/13802499/gdb.txt)
[raze-crash.log](https://github.com/ZDoom/Raze/files/13802500/raze-crash.log)

[raze.ini.txt](https://github.com/ZDoom/Raze/files/13802501/raze.ini.txt)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Attempt to run game.

**Comment by coelckers** [comment]
looks to be the same as what was fixed in ac8e80e52f15987971a0f2bacdddfac79e840c6b

**Comment by daemonspudguy** [comment]
Nope, didn't fix anything. New logs are here.
[gdb.txt](https://github.com/ZDoom/Raze/files/13806232/gdb.txt)
[raze-crash.log](https://github.com/ZDoom/Raze/files/13806233/raze-crash.log)

**Comment by daemonspudguy** [comment]
@coelckers didn't do anything at all.
