### ISSUE TITLE
[BUG] [Shadow Warrior] I can choose Russian language but font doesn't support characters fully

### ISSUE THREAD

**Issue by Blueberryy** [ZDoom/Raze#1055]
### Raze version

1.9.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![image](https://github.com/ZDoom/Raze/assets/36592509/5efc674a-bade-4180-9699-f2a6f6cf2b81)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download latest Raze
2. Have Shadow Warrior installed on Steam
3. Run Raze and choose Russian language on miscellaneous settings

**Comment by coelckers** [comment]
fixed in 4f8207a73f35999db6d2a8383f353ae7191d3ac4

I made all these plus some more last February, but they were never added to the project... :(

**Comment by Blueberryy** [comment]
> fixed in 4f8207a73f35999db6d2a8383f353ae7191d3ac4
> 
> I made all these plus some more last February, but they were never added to the project... :(

Yeah and some fonts still missing russian characters; Exhumed Powerslave and other game that i need to investigate

**Comment by Blueberryy** [comment]
So here's list of not uploaded/finished fonts for Russian characters:
- Exhumed: BigFont, Smallfont
- Redneck: Smallfont

**Comment by Blueberryy** [comment]
Thank you @coelckers for your hard work on fonts! This is really impressive. Please update localization file if you will be creating version 1.9.2

**Comment by Blueberryy** [comment]
Now there's all characters. Thank you once again coelckers! 🎊
