### ISSUE TITLE
[BUG] Duke3D - Render Issue E5M1 & E3M8

### ISSUE THREAD

**Issue by Axldomi** [ZDoom/Raze#865]
### Raze version

1.6.2.

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

See screenshot below:

![Duke_0002](https://user-images.githubusercontent.com/71838912/213860020-7e8ccf17-5f12-473c-b87a-a76c3dc042c4.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to E5M1
2. Go towards the final room in the level (beyond yellow key room)
3. Look up

**Comment by coelckers** [comment]
There is no render issue here. That room uses two different sky light levels on the 'light side' and 'dark side'. Obviously that extends into infinity when looking up, which admittedly does not look that great - but it is how the level was designed.

**Comment by Axldomi** [comment]
I understand... but this was rendered perfectly in Raze 1.4.1:

![Duke_0000](https://user-images.githubusercontent.com/71838912/214941804-190f60c4-9a95-4c38-a6fc-4960470e176e.png)

**Comment by Axldomi** [comment]
Moreover... there are other examples as well. Just go to the second floor in Hotel Hell (E3M8).

In Raze 1.4.1 you get this:

![1 4 1](https://user-images.githubusercontent.com/71838912/214942414-5a1b2e14-fae5-4498-8377-33effd7a666a.png)

In Raze 1.6.2, you get this:

![1 6 2](https://user-images.githubusercontent.com/71838912/214942975-89d05246-5a26-4f31-81cf-f48f56b6e58d.png)

**Comment by coelckers** [comment]
That piece of code was changed AFTER 1.4.1 after someone reported that the sky was not rendered properly in E5L1. So citing that as the proper behavior is not right.

**Comment by coelckers** [comment]
Thanks. This means that original report was bogus.

**Comment by coelckers** [comment]
fixed in acac74715fe55a7a3ee409be15184c52abf75968

**Comment by Axldomi** [comment]
It seems the issue is back... using the latest Raze version:

![Duke_0002](https://user-images.githubusercontent.com/71838912/229304971-4fdffeee-de59-454f-87c3-053b0657cfc8.png)

**Comment by coelckers** [comment]
It's not in the current master
