### ISSUE TITLE
[BUG] Hovercar on E1L2 spawns when it should not

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#913]
### Raze version

1.8pre-100-g 2ba204444c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On Duke Nukem E1L2, playing on "Piece of Cake", there is a hovercar that spawns when it should not. The hovercar spawns when the player picks up the blue keycard, and it just does nothing.

I say it shouldn't spawn because I just tried playing E1L2 in Duke Nukem 3D: Megaton Edition, and the bugged hovercar did not spawn at all.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11180131/sleeping.vehicle.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on E1L2, on the "Piece of Cake" difficulty
2. Play until you get the blue keycard
3. A hovercar spawns near the blue keycard building, and does nothing.

**Comment by coelckers** [comment]
fixed in e2db4a834ece73b88f2c49f0e818d22babed5d11

All thanks to the totally convoluted actor init code. Normally all enemies get a default scale - EXCEPT the recon which is not scripted and doesn't have any code to set a default. This very special edge case got lost when the code was cleaned up.

**Comment by FitzRoyX** [comment]
Started a new game on the latest master this morning and this still happens for me. Here's a save. I believe the spawn triggers when you enter the room above this elevator.

[save0000.zip](https://github.com/ZDoom/Raze/files/11190672/save0000.zip)
